songs/pl/poezja/Zycie_to_nie_teatr.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-06-22-3371-pl_poezja_Zycie_to_nie_teatr.xml&file=songs%2Fpl%2Fpoezja%2FZycie_to_nie_teatr.xml&user=ptabor)
Piosenka Życie to nie teatr: Initial
Piosenka Życie to nie teatr: Spacje
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-06-22-3371-pl_poezja_Zycie_to_nie_teatr.xml&file=songs%2Fpl%2Fpoezja%2FZycie_to_nie_teatr.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Zycie_to_nie_teatr.xml

songs/pl/poezja/Chory_na_wyobraznie.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-06-22-2478-pl_poezja_Chory_na_wyobraznie.xml&file=songs%2Fpl%2Fpoezja%2FChory_na_wyobraznie.xml&user=ptabor)
Piosenka Chory na wyobraźnię: Initial
Piosenka Chory na wyobraźnię: Drobne poprawki
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-06-22-2478-pl_poezja_Chory_na_wyobraznie.xml&file=songs%2Fpl%2Fpoezja%2FChory_na_wyobraznie.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Chory_na_wyobraznie.xml

src/html/create_songs_html.py, src/html/css/common.css
- **Viewport should help with scaling the songs on mobile.**
- **Zoom out by default.**
- **Turn off line height.**
=> 20250622 fix scaling mobile

editor/songbook.js, src/html/css/index.css, src/html/css/song_common.css, src/html/templates/index.xhtml
- **Correct CSS for mobile devices.**
- **Remove hardcoded URL: europe-west1-wdw-21**
=> 20250703 mobile css

songs/pl/pop/pila_tango.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-03-2025-pl_pop_pila_tango.xml&file=songs%2Fpl%2Fpop%2Fpila_tango.xml&user=ptabor)
Piosenka Piła tango: Muzyka w pierwszej zwrotce
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-03-2025-pl_pop_pila_tango.xml&file=songs%2Fpl%2Fpop%2Fpila_tango.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/pila_tango.xml

editor/sanitize.js, editor/songbook.js, src/html/css/index.css, src/html/css/song_common.css, src/html/templates/index.xhtml
- **Correct CSS for mobile devices.**
- **Remove hardcoded URL: europe-west1-wdw-21**
- **Better support for import.**
=> Better support for import of not breakable text

songs/pl/harc/sosenka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-6931-pl_harc_sosenka.xml&file=songs%2Fpl%2Fharc%2Fsosenka.xml&user=ptabor)
Piosenka Sosenka: Sosenka
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-6931-pl_harc_sosenka.xml&file=songs%2Fpl%2Fharc%2Fsosenka.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/sosenka.xml

songs/pl/kabaret/jajko.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-8060-pl_kabaret_jajko.xml&file=songs%2Fpl%2Fkabaret%2Fjajko.xml&user=ptabor)
Piosenka Jajko: Jajko
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-8060-pl_kabaret_jajko.xml&file=songs%2Fpl%2Fkabaret%2Fjajko.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/jajko.xml

songs/pl/folk/lipka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-19-pl_folk_lipka.xml&file=songs%2Fpl%2Ffolk%2Flipka.xml&user=ptabor)
Piosenka Lipka: Lipka
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-19-pl_folk_lipka.xml&file=songs%2Fpl%2Ffolk%2Flipka.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/lipka.xml

songs/pl/harc/maly_oboz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-9294-pl_harc_maly_oboz.xml&file=songs%2Fpl%2Fharc%2Fmaly_oboz.xml&user=ptabor)
Piosenka Mały obóz: Pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-9294-pl_harc_maly_oboz.xml&file=songs%2Fpl%2Fharc%2Fmaly_oboz.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/maly_oboz.xml

songs/pl/pop/wagnerowski_ton.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-4739-pl_pop_wagnerowski_ton.xml&file=songs%2Fpl%2Fpop%2Fwagnerowski_ton.xml&user=ptabor)
Piosenka Jest taki samotny dom: Wagnerowski ton
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-4739-pl_pop_wagnerowski_ton.xml&file=songs%2Fpl%2Fpop%2Fwagnerowski_ton.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/wagnerowski_ton.xml

songs/pl/pop/Arahia.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-1992-pl_pop_Arahia.xml&file=songs%2Fpl%2Fpop%2FArahia.xml&user=ptabor)
Piosenka Arahja: Pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-05-1992-pl_pop_Arahia.xml&file=songs%2Fpl%2Fpop%2FArahia.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/Arahia.xml

src/html/templates/index.xhtml
- **Fix usability by selecting the search text on focus.**
- **Edits..**
=> Improve search/index webpage 

src/html/templates/index.xhtml
- **Fix usability by selecting the search text on focus.**
- **Edits..**
=> 20250705 search usability improvements

songs/pl/harc/czerwony_plomien.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-6711-pl_harc_czerwony_plomien.xml&file=songs%2Fpl%2Fharc%2Fczerwony_plomien.xml&user=ptabor)
Piosenka Szary mundur 2: Szary Mundur 2
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-6711-pl_harc_czerwony_plomien.xml&file=songs%2Fpl%2Fharc%2Fczerwony_plomien.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/czerwony_plomien.xml

songs/pl/harc/cywilizacja.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-2663-pl_harc_cywilizacja.xml&file=songs%2Fpl%2Fharc%2Fcywilizacja.xml&user=ptabor)
Piosenka Cywilizacja: pierwsza
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-2663-pl_harc_cywilizacja.xml&file=songs%2Fpl%2Fharc%2Fcywilizacja.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/cywilizacja.xml

songs/pl/pop/co_ty_tutaj_robisz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-4891-pl_pop_co_ty_tutaj_robisz.xml&file=songs%2Fpl%2Fpop%2Fco_ty_tutaj_robisz.xml&user=ptabor)
Piosenka Co ty tutaj robisz: Co ty tutaj robisz
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-4891-pl_pop_co_ty_tutaj_robisz.xml&file=songs%2Fpl%2Fpop%2Fco_ty_tutaj_robisz.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/co_ty_tutaj_robisz.xml

songs/pl/szanty/brzeg_nowej_szkocji.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-5490-pl_szanty_brzeg_nowej_szkocji.xml&file=songs%2Fpl%2Fszanty%2Fbrzeg_nowej_szkocji.xml&user=ptabor)
Piosenka Brzegi Nowej Szkocji: Pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-08-5490-pl_szanty_brzeg_nowej_szkocji.xml&file=songs%2Fpl%2Fszanty%2Fbrzeg_nowej_szkocji.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/szanty/brzeg_nowej_szkocji.xml

songs/pl/harc/jezior_blekit.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-463-pl_harc_jezior_blekit.xml&file=songs%2Fpl%2Fharc%2Fjezior_blekit.xml&user=ptabor)
Piosenka Jezior błękit: jezior blekit
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-463-pl_harc_jezior_blekit.xml&file=songs%2Fpl%2Fharc%2Fjezior_blekit.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/jezior_blekit.xml

songs/pl/harc/jak_dobrze_mi.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5055-pl_harc_jak_dobrze_mi.xml&file=songs%2Fpl%2Fharc%2Fjak_dobrze_mi.xml&user=ptabor)
Piosenka Jak dobrze mi: jak dobrze mi
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5055-pl_harc_jak_dobrze_mi.xml&file=songs%2Fpl%2Fharc%2Fjak_dobrze_mi.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/jak_dobrze_mi.xml

songs/pl/harc/iskierka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-1904-pl_harc_iskierka.xml&file=songs%2Fpl%2Fharc%2Fiskierka.xml&user=ptabor)
Piosenka Iskierka: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-1904-pl_harc_iskierka.xml&file=songs%2Fpl%2Fharc%2Fiskierka.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/iskierka.xml

songs/pl/pop/i_love_you.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-8055-pl_pop_i_love_you.xml&file=songs%2Fpl%2Fpop%2Fi_love_you.xml&user=ptabor)
Piosenka I love you: nowa
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-8055-pl_pop_i_love_you.xml&file=songs%2Fpl%2Fpop%2Fi_love_you.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/i_love_you.xml

songs/pl/harc/Harcerskie_wspomnienia.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5132-pl_harc_Harcerskie_wspomnienia.xml&file=songs%2Fpl%2Fharc%2FHarcerskie_wspomnienia.xml&user=ptabor)
Piosenka Harcerskie Wspomnienia: Pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5132-pl_harc_Harcerskie_wspomnienia.xml&file=songs%2Fpl%2Fharc%2FHarcerskie_wspomnienia.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/Harcerskie_wspomnienia.xml

songs/pl/harc/irlandzki_sen.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5245-pl_harc_irlandzki_sen.xml&file=songs%2Fpl%2Fharc%2Firlandzki_sen.xml&user=ptabor)
Piosenka Irlandzki Sen: pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-5245-pl_harc_irlandzki_sen.xml&file=songs%2Fpl%2Fharc%2Firlandzki_sen.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/irlandzki_sen.xml

songs/pl/pop/dlugosc_dzwieku_samotnosci.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-6674-pl_pop_dlugosc_dzwieku_samotnosci.xml&file=songs%2Fpl%2Fpop%2Fdlugosc_dzwieku_samotnosci.xml&user=ptabor)
Piosenka Długość dźwięku samotności: pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-6674-pl_pop_dlugosc_dzwieku_samotnosci.xml&file=songs%2Fpl%2Fpop%2Fdlugosc_dzwieku_samotnosci.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/dlugosc_dzwieku_samotnosci.xml

songs/pl/harc/daktyl.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-1152-pl_harc_daktyl.xml&file=songs%2Fpl%2Fharc%2Fdaktyl.xml&user=ptabor)
Piosenka Daktyl: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-09-1152-pl_harc_daktyl.xml&file=songs%2Fpl%2Fharc%2Fdaktyl.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/daktyl.xml

songs/pl/harc/Major_ponury.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7127-pl_harc_Major_ponury.xml&file=songs%2Fpl%2Fharc%2FMajor_ponury.xml&user=ptabor)
Piosenka Major Ponury: major
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7127-pl_harc_Major_ponury.xml&file=songs%2Fpl%2Fharc%2FMajor_ponury.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/Major_ponury.xml

songs/pl/harc/piosenka_z_szabli.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9570-pl_harc_piosenka_z_szabli.xml&file=songs%2Fpl%2Fharc%2Fpiosenka_z_szabli.xml&user=ptabor)
Piosenka Piosenka z szabli: Karabin
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9570-pl_harc_piosenka_z_szabli.xml&file=songs%2Fpl%2Fharc%2Fpiosenka_z_szabli.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/piosenka_z_szabli.xml

songs/pl/poki_czas.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4706-pl_poki_czas.xml&file=songs%2Fpl%2Fpoki_czas.xml&user=ptabor)
Piosenka Obietnica: Obietnica
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4706-pl_poki_czas.xml&file=songs%2Fpl%2Fpoki_czas.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poki_czas.xml

songs/pl/folk/niemanie.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7588-pl_folk_niemanie.xml&file=songs%2Fpl%2Ffolk%2Fniemanie.xml&user=ptabor)
Piosenka Niemanie: Spiewnik
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7588-pl_folk_niemanie.xml&file=songs%2Fpl%2Ffolk%2Fniemanie.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/niemanie.xml

songs/pl/pop/na_jednej_z_dzikich_plaz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-8424-pl_pop_na_jednej_z_dzikich_plaz.xml&file=songs%2Fpl%2Fpop%2Fna_jednej_z_dzikich_plaz.xml&user=ptabor)
Piosenka Na jednej z dzikich plaż: Lubiła tańczyć
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-8424-pl_pop_na_jednej_z_dzikich_plaz.xml&file=songs%2Fpl%2Fpop%2Fna_jednej_z_dzikich_plaz.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/na_jednej_z_dzikich_plaz.xml

songs/pl/religijne/modlitwa_harcerska.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4034-pl_religijne_modlitwa_harcerska.xml&file=songs%2Fpl%2Freligijne%2Fmodlitwa_harcerska.xml&user=ptabor)
Piosenka Modlitwa harcerska: Modlitwa harc
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4034-pl_religijne_modlitwa_harcerska.xml&file=songs%2Fpl%2Freligijne%2Fmodlitwa_harcerska.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/religijne/modlitwa_harcerska.xml

songs/pl/kabaret/mgla.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9691-pl_kabaret_mgla.xml&file=songs%2Fpl%2Fkabaret%2Fmgla.xml&user=ptabor)
Piosenka Mgła: Mgła
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9691-pl_kabaret_mgla.xml&file=songs%2Fpl%2Fkabaret%2Fmgla.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/mgla.xml

songs/pl/harc/lemata.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-3163-pl_harc_lemata.xml&file=songs%2Fpl%2Fharc%2Flemata.xml&user=ptabor)
Piosenka Łemata: Łemata
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-3163-pl_harc_lemata.xml&file=songs%2Fpl%2Fharc%2Flemata.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/lemata.xml

songs/pl/pop/lubie_mowic_z_toba.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7225-pl_pop_lubie_mowic_z_toba.xml&file=songs%2Fpl%2Fpop%2Flubie_mowic_z_toba.xml&user=ptabor)
Piosenka Lubię mówić z Tobą: I dla tego lubię
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-7225-pl_pop_lubie_mowic_z_toba.xml&file=songs%2Fpl%2Fpop%2Flubie_mowic_z_toba.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/lubie_mowic_z_toba.xml

songs/pl/harc/lody_bambino.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-3136-pl_harc_lody_bambino.xml&file=songs%2Fpl%2Fharc%2Flody_bambino.xml&user=ptabor)
Piosenka Lody (bambino): lody
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-3136-pl_harc_lody_bambino.xml&file=songs%2Fpl%2Fharc%2Flody_bambino.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/lody_bambino.xml

songs/pl/harc/kolor_zielony.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9404-pl_harc_kolor_zielony.xml&file=songs%2Fpl%2Fharc%2Fkolor_zielony.xml&user=ptabor)
Piosenka Kolor zielony: Kolor zielony
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9404-pl_harc_kolor_zielony.xml&file=songs%2Fpl%2Fharc%2Fkolor_zielony.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/kolor_zielony.xml

songs/pl/naucz_sie_kochac_mnie_w_rytmie_reggae.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9005-pl_naucz_sie_kochac_mnie_w_rytmie_reggae.xml&file=songs%2Fpl%2Fnaucz_sie_kochac_mnie_w_rytmie_reggae.xml&user=ptabor)
Piosenka Naucz się kochać mnie w rytmie reggae: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-9005-pl_naucz_sie_kochac_mnie_w_rytmie_reggae.xml&file=songs%2Fpl%2Fnaucz_sie_kochac_mnie_w_rytmie_reggae.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/naucz_sie_kochac_mnie_w_rytmie_reggae.xml

songs/pl/pop/ostatnia_nocka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4121-pl_pop_ostatnia_nocka.xml&file=songs%2Fpl%2Fpop%2Fostatnia_nocka.xml&user=ptabor)
Piosenka Ostatnia nocka: Ostatnia nocka
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-10-4121-pl_pop_ostatnia_nocka.xml&file=songs%2Fpl%2Fpop%2Fostatnia_nocka.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/ostatnia_nocka.xml

songs/pl/harc/plastikowa_biedronko.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-7312-pl_harc_plastikowa_biedronko.xml&file=songs%2Fpl%2Fharc%2Fplastikowa_biedronko.xml&user=ptabor)
Piosenka Plastikowa biedronka: plast
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-7312-pl_harc_plastikowa_biedronko.xml&file=songs%2Fpl%2Fharc%2Fplastikowa_biedronko.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/plastikowa_biedronko.xml

songs/pl/harc/zostanie_tyle_gor.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-8704-pl_harc_zostanie_tyle_gor.xml&file=songs%2Fpl%2Fharc%2Fzostanie_tyle_gor.xml&user=ptabor)
Piosenka Zostanie tyle gór: Piosenka turystyczna
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-8704-pl_harc_zostanie_tyle_gor.xml&file=songs%2Fpl%2Fharc%2Fzostanie_tyle_gor.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/zostanie_tyle_gor.xml

songs/pl/harc/z_twarza_marylin_monroe.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-2071-pl_harc_z_twarza_marylin_monroe.xml&file=songs%2Fpl%2Fharc%2Fz_twarza_marylin_monroe.xml&user=ptabor)
Piosenka Z twarzą Marylin Monroe: Z Twarzą...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-2071-pl_harc_z_twarza_marylin_monroe.xml&file=songs%2Fpl%2Fharc%2Fz_twarza_marylin_monroe.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/z_twarza_marylin_monroe.xml

songs/pl/harc/wieczorne_spiewogranie.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-8208-pl_harc_wieczorne_spiewogranie.xml&file=songs%2Fpl%2Fharc%2Fwieczorne_spiewogranie.xml&user=ptabor)
Piosenka Wieczorne śpiewogranie: wieczorne spiewogranie
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-8208-pl_harc_wieczorne_spiewogranie.xml&file=songs%2Fpl%2Fharc%2Fwieczorne_spiewogranie.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/wieczorne_spiewogranie.xml

songs/pl/sniegowice.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-9289-pl_sniegowice.xml&file=songs%2Fpl%2Fsniegowice.xml&user=ptabor)
Piosenka Śniegowice: sniegowice
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-9289-pl_sniegowice.xml&file=songs%2Fpl%2Fsniegowice.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/sniegowice.xml

songs/pl/harc/Stokrotka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-940-pl_harc_Stokrotka.xml&file=songs%2Fpl%2Fharc%2FStokrotka.xml&user=ptabor)
Piosenka Stokrotka: Stokrotka
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-940-pl_harc_Stokrotka.xml&file=songs%2Fpl%2Fharc%2FStokrotka.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/Stokrotka.xml

songs/pl/harc/smoczy_blues.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-6487-pl_harc_smoczy_blues.xml&file=songs%2Fpl%2Fharc%2Fsmoczy_blues.xml&user=ptabor)
Piosenka Smoczy Blues: Smoczy Blues
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-6487-pl_harc_smoczy_blues.xml&file=songs%2Fpl%2Fharc%2Fsmoczy_blues.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/smoczy_blues.xml

songs/pl/harc/wspomnienie_bumeranga.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-9229-pl_harc_wspomnienie_bumeranga.xml&file=songs%2Fpl%2Fharc%2Fwspomnienie_bumeranga.xml&user=ptabor)
Piosenka Wspomnienia Bumeranga: wspomnienie bumeranga
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-9229-pl_harc_wspomnienie_bumeranga.xml&file=songs%2Fpl%2Fharc%2Fwspomnienie_bumeranga.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/wspomnienie_bumeranga.xml

songs/pl/poezja/poezja.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-2506-pl_poezja_poezja.xml&file=songs%2Fpl%2Fpoezja%2Fpoezja.xml&user=ptabor)
Piosenka Poezja: poezja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-2506-pl_poezja_poezja.xml&file=songs%2Fpl%2Fpoezja%2Fpoezja.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/poezja.xml

songs/pl/pop/raz_po_raz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-257-pl_pop_raz_po_raz.xml&file=songs%2Fpl%2Fpop%2Fraz_po_raz.xml&user=ptabor)
Piosenka Raz po raz: perfect
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-11-257-pl_pop_raz_po_raz.xml&file=songs%2Fpl%2Fpop%2Fraz_po_raz.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/raz_po_raz.xml

.github/workflows/generate_all.yml, .github/workflows/publish_page.yml, songs/pl/pop/przebudzenie_buzu.xml
- **Missing file.**
- **Add js files.**
- **Sites copying fixes.**
=> Fixes to site deployment code.

songs/pl/pop/pila_tango.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-19-2334-pl_pop_pila_tango.xml&file=null&user=sfc-gh-ptabor)
Piosenka Piła tango: zwrotka
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-07-19-2334-pl_pop_pila_tango.xml&file=null&user=sfc-gh-ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: null

src/html/css/index.css, src/html/templates/index.xhtml
- **Styling fixes.**
- **Remove duplicate.**
- **Fix...**
- **Fix.**
- **Search spiewaj...**
=> 20250720 show and filter artists

src/html/index_generator.py
- **Adding sidemap.xml support.**
- **Fixed.**
=> Add support for generated sitemap

songs/pl/szanty/Na_Mazury.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9900-pl_szanty_Na_Mazury.xml&file=songs%2Fpl%2Fszanty%2FNa_Mazury.xml&user=ptabor)
Piosenka Na Mazury: Initial
Piosenka Na Mazury: Ciapki przy Malfoy
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9900-pl_szanty_Na_Mazury.xml&file=songs%2Fpl%2Fszanty%2FNa_Mazury.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/szanty/Na_Mazury.xml

songs/pl/folk/kwiat_jabloni/drogi_proste.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-1679-pl_folk_kwiat_jabloni_drogi_proste.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdrogi_proste.xml&user=dch-pub)
Piosenka Drogi proste: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-1679-pl_folk_kwiat_jabloni_drogi_proste.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fdrogi_proste.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/drogi_proste.xml

songs/pl/turystyczne/900mil.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-05-2417-pl_turystyczne_900mil.xml&file=songs%2Fpl%2Fturystyczne%2F900mil.xml&user=dch-pub)
Piosenka 900 mil: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-05-2417-pl_turystyczne_900mil.xml&file=songs%2Fpl%2Fturystyczne%2F900mil.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/900mil.xml

songs/pl/turystyczne/piosenka_kociolka.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-05-9837-pl_turystyczne_piosenka_kociolka.xml&file=songs%2Fpl%2Fturystyczne%2Fpiosenka_kociolka.xml&user=dch-pub)
Piosenka Piosenka kociołka: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-05-9837-pl_turystyczne_piosenka_kociolka.xml&file=songs%2Fpl%2Fturystyczne%2Fpiosenka_kociolka.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/piosenka_kociolka.xml

songs/pl/folk/kwiat_jabloni/moglo_byc_nic.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-99-pl_folk_kwiat_jabloni_moglo_byc_nic.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fmoglo_byc_nic.xml&user=dch-pub)
Piosenka Mogło być nic: Initial
Piosenka Mogło być nic: ...wrzucam cały kwiat jabłoni do kategorii Folk
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-99-pl_folk_kwiat_jabloni_moglo_byc_nic.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fmoglo_byc_nic.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/moglo_byc_nic.xml

songs/pl/folk/kwiat_jabloni/niemozliwe.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9188-pl_folk_kwiat_jabloni_niemozliwe.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fniemozliwe.xml&user=dch-pub)
Piosenka Niemożliwe : Initial
Piosenka Niemożliwe : ...Kwiat Jabłoni do Folk
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9188-pl_folk_kwiat_jabloni_niemozliwe.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fniemozliwe.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/niemozliwe.xml

songs/pl/folk/kwiat_jabloni/wodymidaj.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9089-pl_folk_kwiat_jabloni_wodymidaj.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwodymidaj.xml&user=dch-pub)
Piosenka Wodymidaj: ...kwiat jabłoni do folku
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-9089-pl_folk_kwiat_jabloni_wodymidaj.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwodymidaj.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/wodymidaj.xml

songs/pl/folk/kwiat_jabloni/wzieli_zamkneli_mi_klub.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-647-pl_folk_kwiat_jabloni_wzieli_zamkneli_mi_klub.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwzieli_zamkneli_mi_klub.xml&user=dch-pub)
Piosenka Wzięli zamknęli mi klub: ...kwiat jabłoni do folku
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-647-pl_folk_kwiat_jabloni_wzieli_zamkneli_mi_klub.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fwzieli_zamkneli_mi_klub.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/wzieli_zamkneli_mi_klub.xml

songs/pl/folk/kwiat_jabloni/za_siodma_gora.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-4913-pl_folk_kwiat_jabloni_za_siodma_gora.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fza_siodma_gora.xml&user=dch-pub)
Piosenka Za siódmą chmurą: Initial
Piosenka Za siódmą chmurą: ...kwiat jabłoni do folku
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-4913-pl_folk_kwiat_jabloni_za_siodma_gora.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fza_siodma_gora.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/za_siodma_gora.xml

songs/pl/folk/kwiat_jabloni/turysta.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-3750-pl_folk_kwiat_jabloni_turysta.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fturysta.xml&user=dch-pub)
Piosenka Turysta: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-3750-pl_folk_kwiat_jabloni_turysta.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fturysta.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/turysta.xml

songs/pl/folk/kwiat_jabloni/przezroczysty_swiat.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-7622-pl_folk_kwiat_jabloni_przezroczysty_swiat.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fprzezroczysty_swiat.xml&user=dch-pub)
Piosenka Przezroczysty Świat: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-7622-pl_folk_kwiat_jabloni_przezroczysty_swiat.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fprzezroczysty_swiat.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/przezroczysty_swiat.xml

songs/pl/folk/kwiat_jabloni/nic_wiecej.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-8492-pl_folk_kwiat_jabloni_nic_wiecej.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fnic_wiecej.xml&user=dch-pub)
Piosenka Nic więcej: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-04-8492-pl_folk_kwiat_jabloni_nic_wiecej.xml&file=songs%2Fpl%2Ffolk%2Fkwiat_jabloni%2Fnic_wiecej.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/folk/kwiat_jabloni/nic_wiecej.xml

songs/pl/turystyczne/balladazgor.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-7209-pl_turystyczne_balladazgor.xml&file=songs%2Fpl%2Fturystyczne%2Fballadazgor.xml&user=dch-pub)
Piosenka Ballada z gór: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-7209-pl_turystyczne_balladazgor.xml&file=songs%2Fpl%2Fturystyczne%2Fballadazgor.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/balladazgor.xml

songs/pl/turystyczne/blekitny_Czas.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-6645-pl_turystyczne_blekitny_Czas.xml&file=songs%2Fpl%2Fturystyczne%2Fblekitny_Czas.xml&user=dch-pub)
Piosenka Błękitny czas: ...nowa
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-6645-pl_turystyczne_blekitny_Czas.xml&file=songs%2Fpl%2Fturystyczne%2Fblekitny_Czas.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/blekitny_Czas.xml

songs/pl/poezja/Jest_juz_za_pozno_nie_jest_za_pozno.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-5067-pl_poezja_Jest_juz_za_pozno_nie_jest_za_pozno.xml&file=songs%2Fpl%2Fpoezja%2FJest_juz_za_pozno_nie_jest_za_pozno.xml&user=dch-pub)
Piosenka Jest już za późno, nie jest za późno: Initial
Piosenka Jest już za późno, nie jest za późno: ... poprawione akordy w ostatniej zwrotce. moim zdaniem lepiej, a te H7 tam nie leżały
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-5067-pl_poezja_Jest_juz_za_pozno_nie_jest_za_pozno.xml&file=songs%2Fpl%2Fpoezja%2FJest_juz_za_po …
=> Piosenka: songs/pl/poezja/Jest_juz_za_pozno_nie_jest_za_pozno.xml

songs/pl/kabaret/plastikowa_biedronko.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-3443-pl_kabaret_plastikowa_biedronko.xml&file=songs%2Fpl%2Fkabaret%2Fplastikowa_biedronko.xml&user=dch-pub)
Piosenka Pastikowa Biedronka: Initial
Piosenka Pastikowa Biedronka: ...zmiana słów, mozna się spierać ale poproszę aby zwrotka o pingwinie i tak gdzieś została.
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-3443-pl_kabaret_plastikowa_biedronko.xml&file=songs%2Fpl%2Fkabaret%2Fplastikowa_biedronko.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/plastikowa_biedronko.xml

songs/pl/poezja/Opadly_mgly_wstaje_nowy_dzien.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-2937-pl_poezja_Opadly_mgly_wstaje_nowy_dzien.xml&file=songs%2Fpl%2Fpoezja%2FOpadly_mgly_wstaje_nowy_dzien.xml&user=dch-pub)
Piosenka Opadły mgły wstaje nowy dzień: ...poprawiłam chwyty w zwrotce 2
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-07-2937-pl_poezja_Opadly_mgly_wstaje_nowy_dzien.xml&file=songs%2Fpl%2Fpoezja%2FOpadly_mgly_wstaje_nowy_dzien.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Opadly_mgly_wstaje_nowy_dzien.xml

songs/pl/poezja/ballada_o_nocy_czerwcowej.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-06-6265-pl_poezja_ballada_o_nocy_czerwcowej.xml&file=songs%2Fpl%2Fpoezja%2Fballada_o_nocy_czerwcowej.xml&user=dch-pub)
Piosenka Ballada o nocy czerwcowej: ...zaznaczone akordy opcjonalne itp
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-06-6265-pl_poezja_ballada_o_nocy_czerwcowej.xml&file=songs%2Fpl%2Fpoezja%2Fballada_o_nocy_czerwcowej.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/ballada_o_nocy_czerwcowej.xml

songs/pl/bardowie/Kwiecien74.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-2938-pl_bardowie_Kwiecien74.xml&file=songs%2Fpl%2Fbardowie%2FKwiecien74.xml&user=ptabor)
Piosenka Kwiecień '74: pierwsza wersja
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-2938-pl_bardowie_Kwiecien74.xml&file=songs%2Fpl%2Fbardowie%2FKwiecien74.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/bardowie/Kwiecien74.xml

songs/pl/turystyczne/podjablonia.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-1106-pl_turystyczne_podjablonia.xml&file=songs%2Fpl%2Fturystyczne%2Fpodjablonia.xml&user=dch-pub)
Piosenka Pod jabłonią: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-1106-pl_turystyczne_podjablonia.xml&file=songs%2Fpl%2Fturystyczne%2Fpodjablonia.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/podjablonia.xml

songs/pl/poezja/kiedymiwesolo.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-4399-pl_poezja_kiedymiwesolo.xml&file=songs%2Fpl%2Fpoezja%2Fkiedymiwesolo.xml&user=dch-pub)
Piosenka Kiedy mi wesoło: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-4399-pl_poezja_kiedymiwesolo.xml&file=songs%2Fpl%2Fpoezja%2Fkiedymiwesolo.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/kiedymiwesolo.xml

songs/pl/turystyczne/odTurbacza.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-9227-pl_turystyczne_odTurbacza.xml&file=songs%2Fpl%2Fturystyczne%2FodTurbacza.xml&user=dch-pub)
Piosenka Od Turbacza: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-9227-pl_turystyczne_odTurbacza.xml&file=songs%2Fpl%2Fturystyczne%2FodTurbacza.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/odTurbacza.xml

songs/pl/turystyczne/pustowgorcach.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-3824-pl_turystyczne_pustowgorcach.xml&file=songs%2Fpl%2Fturystyczne%2Fpustowgorcach.xml&user=dch-pub)
Piosenka Pusto w Gorcach: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-12-3824-pl_turystyczne_pustowgorcach.xml&file=songs%2Fpl%2Fturystyczne%2Fpustowgorcach.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/pustowgorcach.xml

songs/pl/poezja/Czarny_blues_o_czwartej_nad_ranem.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-14-6591-pl_poezja_Czarny_blues_o_czwartej_nad_ranem.xml&file=songs%2Fpl%2Fpoezja%2FCzarny_blues_o_czwartej_nad_ranem.xml&user=ptabor)
Piosenka Czarny blues o czwartej nad ranem: ... czwarta
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-14-6591-pl_poezja_Czarny_blues_o_czwartej_nad_ranem.xml&file=songs%2Fpl%2Fpoezja%2FCzarny_blues_o_czwartej_nad_ranem.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Czarny_blues_o_czwartej_nad_ranem.xml

songs/pl/poezja/Piosenka_bez_tytulu.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-13-4626-pl_poezja_Piosenka_bez_tytulu.xml&file=songs%2Fpl%2Fpoezja%2FPiosenka_bez_tytulu.xml&user=dch-pub)
Piosenka Piosenka bez tytułu: Initial
Piosenka Piosenka bez tytułu: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-13-4626-pl_poezja_Piosenka_bez_tytulu.xml&file=songs%2Fpl%2Fpoezja%2FPiosenka_bez_tytulu.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Piosenka_bez_tytulu.xml

songs/pl/kabaret/dobranoc.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-15-2556-pl_kabaret_dobranoc.xml&file=songs%2Fpl%2Fkabaret%2Fdobranoc.xml&user=ptabor)
Piosenka Dobranoc: Kluczowe akrody
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-15-2556-pl_kabaret_dobranoc.xml&file=songs%2Fpl%2Fkabaret%2Fdobranoc.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/dobranoc.xml

songs/pl/poezja/Ballada_o_krzyzowcu.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-14-2183-pl_poezja_Ballada_o_krzyzowcu.xml&file=songs%2Fpl%2Fpoezja%2FBallada_o_krzyzowcu.xml&user=ptabor)
Piosenka Ballada o krzyżowcu: Initial
Piosenka Ballada o krzyżowcu: ... krzyżowiec
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-14-2183-pl_poezja_Ballada_o_krzyzowcu.xml&file=songs%2Fpl%2Fpoezja%2FBallada_o_krzyzowcu.xml&user=ptabor) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Ballada_o_krzyzowcu.xml

songs/en/basi/six-feet-under.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-2457-en_basi_six-feet-under.xml&file=songs%2Fen%2Fbasi%2Fsix-feet-under.xml&user=ropucha2137)
Piosenka Six feet under: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-2457-en_basi_six-feet-under.xml&file=songs%2Fen%2Fbasi%2Fsix-feet-under.xml&user=ropucha2137) by nanieść dodatkowe poprawki.
=> Piosenka: songs/en/basi/six-feet-under.xml

songs/pl/harc/pechowy_dzien.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-2961-pl_harc_pechowy_dzien.xml&file=songs%2Fpl%2Fharc%2Fpechowy_dzien.xml&user=dch-pub)
Piosenka Pechowy Dzień: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-2961-pl_harc_pechowy_dzien.xml&file=songs%2Fpl%2Fharc%2Fpechowy_dzien.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/harc/pechowy_dzien.xml

songs/pl/poezja/Nuta_z_Ponidzia.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-8898-pl_poezja_Nuta_z_Ponidzia.xml&file=songs%2Fpl%2Fpoezja%2FNuta_z_Ponidzia.xml&user=dch-pub)
Piosenka Nuta z Ponidzia: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-8898-pl_poezja_Nuta_z_Ponidzia.xml&file=songs%2Fpl%2Fpoezja%2FNuta_z_Ponidzia.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Nuta_z_Ponidzia.xml

songs/pl/turystyczne/sponad_kufla_piwa.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-1709-pl_turystyczne_sponad_kufla_piwa.xml&file=songs%2Fpl%2Fturystyczne%2Fsponad_kufla_piwa.xml&user=dch-pub)
Piosenka Sponad kufla piwa: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-21-1709-pl_turystyczne_sponad_kufla_piwa.xml&file=songs%2Fpl%2Fturystyczne%2Fsponad_kufla_piwa.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/sponad_kufla_piwa.xml

songs/pl/poezja/jam_DoZP.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-645-pl_poezja_jam_DoZP.xml&file=songs%2Fpl%2Fpoezja%2Fjam_DoZP.xml&user=dch-pub)
Piosenka Jam: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-645-pl_poezja_jam_DoZP.xml&file=songs%2Fpl%2Fpoezja%2Fjam_DoZP.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/jam_DoZP.xml

songs/pl/poezja/pioseka_dla_doski.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-1102-pl_poezja_pioseka_dla_doski.xml&file=songs%2Fpl%2Fpoezja%2Fpioseka_dla_doski.xml&user=dch-pub)
Piosenka Piosenka dla Dośki: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-1102-pl_poezja_pioseka_dla_doski.xml&file=songs%2Fpl%2Fpoezja%2Fpioseka_dla_doski.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/pioseka_dla_doski.xml

songs/pl/poezja/bociany_nabani.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5313-pl_poezja_bociany_nabani.xml&file=songs%2Fpl%2Fpoezja%2Fbociany_nabani.xml&user=dch-pub)
Piosenka Lecące bociany: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5313-pl_poezja_bociany_nabani.xml&file=songs%2Fpl%2Fpoezja%2Fbociany_nabani.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/bociany_nabani.xml

songs/pl/turystyczne/bossanova_na4rece.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-9642-pl_turystyczne_bossanova_na4rece.xml&file=songs%2Fpl%2Fturystyczne%2Fbossanova_na4rece.xml&user=dch-pub)
Piosenka Bossanova na 4 ręce: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-9642-pl_turystyczne_bossanova_na4rece.xml&file=songs%2Fpl%2Fturystyczne%2Fbossanova_na4rece.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/bossanova_na4rece.xml

songs/pl/poezja/tu_asfalt_sie_konczy.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5306-pl_poezja_tu_asfalt_sie_konczy.xml&file=songs%2Fpl%2Fpoezja%2Ftu_asfalt_sie_konczy.xml&user=dch-pub)
Piosenka Tu asfalt się kończy: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5306-pl_poezja_tu_asfalt_sie_konczy.xml&file=songs%2Fpl%2Fpoezja%2Ftu_asfalt_sie_konczy.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/tu_asfalt_sie_konczy.xml

songs/pl/turystyczne/asfalt.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-7302-pl_turystyczne_asfalt.xml&file=songs%2Fpl%2Fturystyczne%2Fasfalt.xml&user=dch-pub)
Piosenka Asfalt: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-7302-pl_turystyczne_asfalt.xml&file=songs%2Fpl%2Fturystyczne%2Fasfalt.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/asfalt.xml

songs/pl/poezja/aty_tancz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5082-pl_poezja_aty_tancz.xml&file=songs%2Fpl%2Fpoezja%2Faty_tancz.xml&user=dch-pub)
Piosenka A ty tańcz: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5082-pl_poezja_aty_tancz.xml&file=songs%2Fpl%2Fpoezja%2Faty_tancz.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/aty_tancz.xml

songs/pl/poezja/babe_zeslal_bog.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5936-pl_poezja_babe_zeslal_bog.xml&file=songs%2Fpl%2Fpoezja%2Fbabe_zeslal_bog.xml&user=dch-pub)
Piosenka Babę zesłał Bóg: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-5936-pl_poezja_babe_zeslal_bog.xml&file=songs%2Fpl%2Fpoezja%2Fbabe_zeslal_bog.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/babe_zeslal_bog.xml

songs/pl/turystyczne/bieszczadzki_ekspres.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-9204-pl_turystyczne_bieszczadzki_ekspres.xml&file=songs%2Fpl%2Fturystyczne%2Fbieszczadzki_ekspres.xml&user=dch-pub)
Piosenka Bieszczadzki ekspres: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-08-22-9204-pl_turystyczne_bieszczadzki_ekspres.xml&file=songs%2Fpl%2Fturystyczne%2Fbieszczadzki_ekspres.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/bieszczadzki_ekspres.xml

songs/pl/poezja/Pejzaze_harasymowiczowskie.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4068-pl_poezja_Pejzaze_harasymowiczowskie.xml&file=songs%2Fpl%2Fpoezja%2FPejzaze_harasymowiczowskie.xml&user=dch-pub)
Piosenka Pejzaże harasymowiczowskie: Initial
Piosenka Pejzaże harasymowiczowskie: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4068-pl_poezja_Pejzaze_harasymowiczowskie.xml&file=songs%2Fpl%2Fpoezja%2FPejzaze_harasymowiczowskie.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Pejzaze_harasymowiczowskie.xml

songs/pl/poezja/czarny_leb_slonecznika.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-3416-pl_poezja_czarny_leb_slonecznika.xml&file=songs%2Fpl%2Fpoezja%2Fczarny_leb_slonecznika.xml&user=dch-pub)
Piosenka Czarny łeb słonecznika: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-3416-pl_poezja_czarny_leb_slonecznika.xml&file=songs%2Fpl%2Fpoezja%2Fczarny_leb_slonecznika.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/czarny_leb_slonecznika.xml

songs/pl/pop/piosenka_ksiezycowa.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8861-pl_pop_piosenka_ksiezycowa.xml&file=songs%2Fpl%2Fpop%2Fpiosenka_ksiezycowa.xml&user=dch-pub)
Piosenka Piosenka księżycowa: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8861-pl_pop_piosenka_ksiezycowa.xml&file=songs%2Fpl%2Fpop%2Fpiosenka_ksiezycowa.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/piosenka_ksiezycowa.xml

songs/pl/szanty/Pogodne_popoludnie_kapitana_bialej_floty.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-186-pl_szanty_Pogodne_popoludnie_kapitana_bialej_floty.xml&file=songs%2Fpl%2Fszanty%2FPogodne_popoludnie_kapitana_bialej_floty.xml&user=dch-pub)
Piosenka Pogodne popołudnie kapitana białej floty: Initial
Piosenka Pogodne popołudnie kapitana białej floty: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-186-pl_szanty_Pogodne_popoludnie_kapitana_bialej_floty.xml&file=songs%2Fpl%2Fszanty%2FPogodne_popoludnie_kapitana_bialej_floty.xml&user=dch-pub) by nanieść …
=> Piosenka: songs/pl/szanty/Pogodne_popoludnie_kapitana_bialej_floty.xml

songs/pl/pop/zanim_zrozumiesz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-7443-pl_pop_zanim_zrozumiesz.xml&file=songs%2Fpl%2Fpop%2Fzanim_zrozumiesz.xml&user=dch-pub)
Piosenka Zanim zrozumiesz: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-7443-pl_pop_zanim_zrozumiesz.xml&file=songs%2Fpl%2Fpop%2Fzanim_zrozumiesz.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/zanim_zrozumiesz.xml

songs/pl/poezja/Zapisze_sniegiem_w_kominie.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2941-pl_poezja_Zapisze_sniegiem_w_kominie.xml&file=songs%2Fpl%2Fpoezja%2FZapisze_sniegiem_w_kominie.xml&user=dch-pub)
Piosenka Zapiszę śniegiem w kominie: Initial
Piosenka Zapiszę śniegiem w kominie: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2941-pl_poezja_Zapisze_sniegiem_w_kominie.xml&file=songs%2Fpl%2Fpoezja%2FZapisze_sniegiem_w_kominie.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Zapisze_sniegiem_w_kominie.xml

songs/pl/poezja/deesis.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2102-pl_poezja_deesis.xml&file=songs%2Fpl%2Fpoezja%2Fdeesis.xml&user=dch-pub)
Piosenka Deesis: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2102-pl_poezja_deesis.xml&file=songs%2Fpl%2Fpoezja%2Fdeesis.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/deesis.xml

songs/pl/turystyczne/orawa.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-9846-pl_turystyczne_orawa.xml&file=songs%2Fpl%2Fturystyczne%2Forawa.xml&user=dch-pub)
Piosenka Orawa: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-9846-pl_turystyczne_orawa.xml&file=songs%2Fpl%2Fturystyczne%2Forawa.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/orawa.xml

songs/pl/poezja/sosna.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-136-pl_poezja_sosna.xml&file=songs%2Fpl%2Fpoezja%2Fsosna.xml&user=dch-pub)
Piosenka Sosna: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-136-pl_poezja_sosna.xml&file=songs%2Fpl%2Fpoezja%2Fsosna.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/sosna.xml

songs/pl/poezja/znalezione.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8614-pl_poezja_znalezione.xml&file=songs%2Fpl%2Fpoezja%2Fznalezione.xml&user=dch-pub)
Piosenka Znalezione: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8614-pl_poezja_znalezione.xml&file=songs%2Fpl%2Fpoezja%2Fznalezione.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/znalezione.xml

songs/pl/turystyczne/ballada_na3chwyty.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-3674-pl_turystyczne_ballada_na3chwyty.xml&file=songs%2Fpl%2Fturystyczne%2Fballada_na3chwyty.xml&user=dch-pub)
Piosenka Ballada na trzy chwyty czyli bardzo prosta piosenka o kobietach: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-3674-pl_turystyczne_ballada_na3chwyty.xml&file=songs%2Fpl%2Fturystyczne%2Fballada_na3chwyty.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/turystyczne/ballada_na3chwyty.xml

songs/pl/pop/dziwna_daria.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2363-pl_pop_dziwna_daria.xml&file=songs%2Fpl%2Fpop%2Fdziwna_daria.xml&user=dch-pub)
Piosenka Dziwna: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2363-pl_pop_dziwna_daria.xml&file=songs%2Fpl%2Fpop%2Fdziwna_daria.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/dziwna_daria.xml

songs/pl/kabaret/cieszynska.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4647-pl_kabaret_cieszynska.xml&file=songs%2Fpl%2Fkabaret%2Fcieszynska.xml&user=dch-pub)
Piosenka Cieszyńska: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4647-pl_kabaret_cieszynska.xml&file=songs%2Fpl%2Fkabaret%2Fcieszynska.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/cieszynska.xml

songs/pl/kabaret/dus_golabki.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-9235-pl_kabaret_dus_golabki.xml&file=songs%2Fpl%2Fkabaret%2Fdus_golabki.xml&user=dch-pub)
Piosenka Duś, duś gołąbki: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-9235-pl_kabaret_dus_golabki.xml&file=songs%2Fpl%2Fkabaret%2Fdus_golabki.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/dus_golabki.xml

songs/pl/kabaret/glanki_pacyfki.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8970-pl_kabaret_glanki_pacyfki.xml&file=songs%2Fpl%2Fkabaret%2Fglanki_pacyfki.xml&user=dch-pub)
Piosenka Glanki i Pacyfki: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-8970-pl_kabaret_glanki_pacyfki.xml&file=songs%2Fpl%2Fkabaret%2Fglanki_pacyfki.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/glanki_pacyfki.xml

songs/pl/kabaret/orzel_moze.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2678-pl_kabaret_orzel_moze.xml&file=songs%2Fpl%2Fkabaret%2Forzel_moze.xml&user=dch-pub)
Piosenka Orzeł może: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-2678-pl_kabaret_orzel_moze.xml&file=songs%2Fpl%2Fkabaret%2Forzel_moze.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/orzel_moze.xml

songs/pl/kabaret/podryw_na_misia.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-5112-pl_kabaret_podryw_na_misia.xml&file=songs%2Fpl%2Fkabaret%2Fpodryw_na_misia.xml&user=dch-pub)
Piosenka Piosenka o podrywie na misia: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-5112-pl_kabaret_podryw_na_misia.xml&file=songs%2Fpl%2Fkabaret%2Fpodryw_na_misia.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/podryw_na_misia.xml

songs/pl/kabaret/zabierzcie_mi_gitare.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-7096-pl_kabaret_zabierzcie_mi_gitare.xml&file=songs%2Fpl%2Fkabaret%2Fzabierzcie_mi_gitare.xml&user=dch-pub)
Piosenka Zabierzcie mi gitarę: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-7096-pl_kabaret_zabierzcie_mi_gitare.xml&file=songs%2Fpl%2Fkabaret%2Fzabierzcie_mi_gitare.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/zabierzcie_mi_gitare.xml

songs/pl/kabaret/zycie_jest_dziwne_ech.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4656-pl_kabaret_zycie_jest_dziwne_ech.xml&file=songs%2Fpl%2Fkabaret%2Fzycie_jest_dziwne_ech.xml&user=dch-pub)
Piosenka Życie jest dziwne: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4656-pl_kabaret_zycie_jest_dziwne_ech.xml&file=songs%2Fpl%2Fkabaret%2Fzycie_jest_dziwne_ech.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/kabaret/zycie_jest_dziwne_ech.xml

songs/pl/poezja/Gor_mi_malo.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4848-pl_poezja_Gor_mi_malo.xml&file=songs%2Fpl%2Fpoezja%2FGor_mi_malo.xml&user=dch-pub)
Piosenka Gór mi mało: Initial
Piosenka Gór mi mało: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-03-4848-pl_poezja_Gor_mi_malo.xml&file=songs%2Fpl%2Fpoezja%2FGor_mi_malo.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/poezja/Gor_mi_malo.xml

_site/index.js, src/html/create_songs_html.py, src/html/css/common.css, src/html/css/index.css, src/html/index_generator.py, src/html/templates/_song_head.xhtml, src/html/templates/_song_prefix.xhtml
- **Site has icons to PDFs near each song.**
- **Per song edit buttons.**
=> Links from songs to PDFs.

songs/pl/pop/warszawa_tlove.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-08-7908-pl_pop_warszawa_tlove.xml&file=songs%2Fpl%2Fpop%2Fwarszawa_tlove.xml&user=dch-pub)
Piosenka Warszawa: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-08-7908-pl_pop_warszawa_tlove.xml&file=songs%2Fpl%2Fpop%2Fwarszawa_tlove.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/warszawa_tlove.xml

songs/pl/pop/lucy_phere.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-08-2238-pl_pop_lucy_phere.xml&file=songs%2Fpl%2Fpop%2Flucy_phere.xml&user=dch-pub)
Piosenka Lucy Phere: ...
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-08-2238-pl_pop_lucy_phere.xml&file=songs%2Fpl%2Fpop%2Flucy_phere.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/lucy_phere.xml

songs/pl/pop/ajrisz.xml
[Link do edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-09-1343-pl_pop_ajrisz.xml&file=songs%2Fpl%2Fpop%2Fajrisz.xml&user=dch-pub)
Możesz zawsze wrócić do [edytora](https://spiewaj.com/editor?baseUrl=https%3A%2F%2Fghe.spiewaj.com&branch=se-2025-09-09-1343-pl_pop_ajrisz.xml&file=songs%2Fpl%2Fpop%2Fajrisz.xml&user=dch-pub) by nanieść dodatkowe poprawki.
=> Piosenka: songs/pl/pop/ajrisz.xml

songbooks/default.songbook.yaml, src/html/index_generator.py, src/lib/songbook.py
- **Add 'lang' attribute to song.**
- **Experimental building of an inddex.**
=> Use relative paths to the list of songs in songbooks.
